/* formatterSettingsOverride */
/*  { "AblFormatter.variableDefinitionFormatting": true} */

DEFINE VARIABLE cName AS CHARACTER NO-UNDO FORMAT "x(30)" INITIAL "Unknown".
DEFINE VARIABLE iAge AS INTEGER NO-UNDO LABEL "Age of Person" INITIAL 0.
DEFINE VARIABLE dBirthDate AS DATE NO-UNDO FORMAT "99/99/9999" INITIAL TODAY.
DEFINE VARIABLE hBuffer AS HANDLE NO-UNDO INITIAL BUFFER Customer:HANDLE.
DEFINE VARIABLE mData AS MEMPTR NO-UNDO INITIAL ?.
DEFINE VARIABLE cJson AS CHARACTER NO-UNDO EXTENT 5 INITIAL ["", "", "", "", ""].
DEFINE VARIABLE rAmount AS DECIMAL NO-UNDO FORMAT "->,>>>,>>9.99" INITIAL 0.
DEFINE VARIABLE lFlag AS LOGICAL NO-UNDO INITIAL FALSE.
DEFINE VARIABLE cXml AS LONGCHAR NO-UNDO INITIAL "".