/* formatterSettingsOverride */
/*  { "AblFormatter.variableDefinitionFormatting": true} */

DEFINE VARIABLE hRowBefore         AS HANDLE    NO-UNDO.
DEFINE VARIABLE cUpdColumnsByTable AS CHARACTER NO-UNDO.
DEFINE VARIABLE hRowUpdFld         AS HANDLE    NO-UNDO.
DEFINE VARIABLE hRowOldFld         AS HANDLE    NO-UNDO.
DEFINE VARIABLE hDBField           AS HANDLE    NO-UNDO.
DEFINE VARIABLE iField             AS INTEGER   NO-UNDO.
DEFINE VARIABLE iTable             AS INTEGER   NO-UNDO.
DEFINE VARIABLE cFromField         AS CHARACTER NO-UNDO.
DEFINE VARIABLE cToField           AS CHARACTER NO-UNDO.
DEFINE VARIABLE lColumnChanged     AS LOGICAL   NO-UNDO.
DEFINE VARIABLE iBracket           AS INTEGER   NO-UNDO.
DEFINE VARIABLE iExtent            AS INTEGER   NO-UNDO.
DEFINE VARIABLE cRowIdent          AS CHARACTER NO-UNDO.
DEFINE VARIABLE cRowid             AS CHARACTER NO-UNDO.
DEFINE VARIABLE cExclude           AS CHARACTER NO-UNDO.
DEFINE VARIABLE cUpdColumns        AS CHARACTER  NO-UNDO.
DEFINE VARIABLE cColumnsByTable    AS CHARACTER  NO-UNDO.
DEFINE VARIABLE cColumns           AS CHARACTER  NO-UNDO.
DEFINE VARIABLE lChanged           AS LOGICAL    NO-UNDO.
DEFINE VARIABLE cNotChanged        AS CHARACTER NO-UNDO.
DEFINE VARIABLE cAssignFields      AS CHARACTER  NO-UNDO.
DEFINE VARIABLE cUseAssignFields   AS CHARACTER  NO-UNDO.
DEFINE VARIABLE cDataColumns       AS CHARACTER  NO-UNDO.
DEFINE VARIABLE lAmbiguous         AS LOGICAL    NO-UNDO.
DEFINE VARIABLE lCreate            AS LOGICAL    NO-UNDO.
DEFINE VARIABLE lLarge             AS LOGICAL    NO-UNDO.
DEFINE VARIABLE cLargeList         AS CHARACTER  NO-UNDO.
DEFINE VARIABLE iLarge             AS INTEGER    NO-UNDO.